const HIGHLIGHT = "#FFFFFF";
const COLD_TEMPERATURE = "#5DADE2";
const WARM_TEMPERATURE = "#CD6155";

const LIGHT_PRIMARY = "#1884F1";
const LIGHT_SECONDARY = "#f4f5fa";
const LIGHT_NEUTRAL = "#f5f5f5";
const LIGHT_BACKGROUND = "#edeef3";
const LIGHT_TEXT_COLOR = "#000000";

const DARK_PRIMARY = "#1B1C21";
const DARK_SECONDARY = "#151419";
const DARK_NEUTRAL = "#898b97";
const DARK_TEXT_COLOR = "#B3B6B7";

const SWITCH_GREEN = "#53d769";
const SWITCH_GREY = "#8e8e93";

export {
    HIGHLIGHT,
    COLD_TEMPERATURE,
    WARM_TEMPERATURE,
    LIGHT_PRIMARY,
    LIGHT_SECONDARY,
    LIGHT_NEUTRAL,
    LIGHT_BACKGROUND,
    LIGHT_TEXT_COLOR,
    DARK_PRIMARY,
    DARK_SECONDARY,
    DARK_NEUTRAL,
    DARK_TEXT_COLOR,
    SWITCH_GREEN,
    SWITCH_GREY
}